# Banco de dados
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/vaidmassas}
spring.datasource.username=${DATABASE_USERNAME:vaidmassas_user}
spring.datasource.password=${DATABASE_PASSWORD:vaidmassas123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=${PORT:8080}