# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/vaidmassas
spring.datasource.username=vaidmassas_user
spring.datasource.password=vaidmassas123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration